#!/bin/bash

protected_branches=("master" "main" "dev")
current_branch=$(git symbolic-ref --short HEAD)

for branch in "${protected_branches[@]}"; do
    if [[ "$current_branch" == "$branch" ]]; then
        echo "You are about to commit to '$current_branch'. This might be very dumb."
        read -p "Are you sure you want to continue? (y/N): " confirm </dev/tty
        confirm=$(echo "$confirm" | tr '[:upper:]' '[:lower:]')

        if [[ "$confirm" != "y" ]]; then
            echo "Commit to '$current_branch' aborted."
            exit 1
        fi
    fi
done
